name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to server
      uses: appleboy/ssh-action@master
      with:
        host: 103.30.194.240
        username: bhq
        password: Mamada90
        
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: naninanides
        password: b4ihaqi90

    - name: Build Docker Image
      run: |
        docker build -t naninanides/bebas:latest .

    - name: Deploy with Docker Compose
      run: |
        docker-compose down
        docker-compose up -d
