name: agforce

on:
  push:
    branches: ["main"]

jobs:
  sonarqube:
    name: sonarqube-scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
  prepare:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - run: |
          git pull https://github.com/naninanides/wayshub-fe.git
  deploy:
    runs-on: self-hosted
    needs: prepare
    steps:
       - run: |
          ls
          docker build -t naninanides/bebas:latest .
          docker compose up -d
