name: agforce

on:
  push:
    branches: ["main"]

jobs:
  sonarqube:
    name: sonarqube-scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
  pull-n-deploy:
    runs-on: self-hosted
    needs: sonarqube
    steps:
      - name: remote server using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            whoami
            ls -a
            git clone https://github.com/naninanides/wayshub-fe.git
            cd wayshub-fe
            git pull origin main
            docker build -t naninanides/bebas:latest .
            docker compose up -d --build
