name: agforce

on:
  push:
    branches: ["main"]

jobs:
  pull-n-deploy:
    runs-on: self-hosted
    steps:
      - name: remote server using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            whoami
            ls -a
            cd wayshub-fe
            git pull origin main
            docker compose up -d --build
