name: agforce

on:
  push:
    branches: ["main"]

jobs:
  pull-n-deploy:
    runs-on: self-hosted
    steps:
      - name: remote server using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            whoami
            ls -a
            git clone https://${{ github.actor }}:${{ github.token }}@github.com/Itgit pull https://${{ github.actor }}:${{ github.token }}@github.com/naninanides/wayshub-fe.git
            cd wayshub-fe
            docker build -t naninanides/bebas:latest .
            docker compose up -d --build
