name: agforce

on:
  push:
    branches: ["master"]

jobs:
  ssh:
    runs-on: self-hosted
    steps:
      - name: remote server using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: prepare
        uses: actions/checkout@v3
        with:
          token: ${{github.token}}
      - run: |
          git pull  https://${{ github.actor }}:${{ github.token }}@github.com/ItsMyEyes/ag_force_cabang_dash.git master

  # prepare:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         token: ${{ github.token }}
  #     - run: |
  #         git pull  https://${{ github.actor }}:${{ github.token }}@github.com/ItsMyEyes/ag_force_cabang_dash.git master
  deploy:
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: app-front
        run: |
          ls
          docker compose -f "docker-compose.yaml" up -d
